[package]
name = "bathtub_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
libc = "0.2.126"

[dev-dependencies]
criterion = "0.4.0"
tempfile = "3.3.0"

[[bench]]
name = "mybench"
harness = false
