[package]
name = "btdb_layer0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.4"
digest = "0.10.3"
generic-array = "0.14.5"

[dev-dependencies]
hex-literal = "0.3.4"
